services:

  eshop-monolith:
    image: ghcr.io/optivem/atdd/eshop-monolith:latest
    ports:
      - "8080:8080"
    environment:
      - ERP_URL=https://optivem.free.beeceptor.com/sap/api
      - SERVER_PORT=8080

  wiremock:
    image: wiremock/wiremock:3.5.2
    ports:
      - "8089:8080"
    environment:
      - WIREMOCK_OPTIONS=--verbose