name: Commit Stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run Docker Compose Up
        run: docker compose up -d

      - name: Build with Gradle Wrapper
        run: ./gradlew build --info --stacktrace

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag eshop-monolith:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag eshop-monolith:${{ github.sha }} ghcr.io/${{ github.repository }}/eshop-monolith:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/eshop-monolith:latest
